# Site - source: https://github.com/sproogen/modern-resume-theme
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyu Hur
title: Software Engineer | Health Researcher

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: kyuhur2
linkedin_username: kyu-hur-143620b6
orcid_username: 0000-0002-0690-345X
additional_links:
  - title: googlescholar
    icon: fab fa-google
    url: https://scholar.google.com/citations?user=p-TpuTsAAAAJ&hl=en
# icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Kyu and I work as a Software Engineer with a keen interest in technological innovations. I strive to build efficient and impactful technological products to solve modern day health and business problems with machine learning. I also have extensive experience in health research as well as mentoring students during my time at the University of Illinois, University of Tokyo, and FPT Software.


  Please utilize the links in the top right to access the following:
  - Github
  - Linkedin
  - Orcid
  - Google Scholar

content:
  - title: Experience (Selected) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Software Engineer
        link: https://www.fpt-software.com/
        link_text: <b>Link to Website</b>
        sub_title: FPT Software
        caption: Feb 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Optimize demand forecasting models on Python, producing 5~10% more accurate forecasts
          -	Saved a projected USD$100,000 a year for a client over the next 3 years
          -	Establish basic standardized systems for projects (pre-commit, code formatting, code linting tools) on Python, saving 80 man-hours per project
          -	Deliver monthly presentations of our SaaS product to clients and external teams in Japan, South Korea, Malaysia, Germany, and the United States
          -	Oversee duties and long-term goals of three junior data scientists

      - layout: left
        title: Research Intern
        link: https://stanford-health.github.io/
        link_text: <b>Link to Website</b>
        sub_title: Stanford University
        caption: Nov 2021 - Present
        description: |
          -	Develop novel data accessibility and data security protocol rating systems of the most popular wearable devices (e.g. Apple Watch) used for clinical settings
          - Draft a chapter of a comprehensive manuscript discussing the role of wearable devices in health research slated for publication in Lancet Digital Health

      - layout: left
        title: Project Researcher
        link: https://www.u-tokyo.ac.jp/en/
        link_text: <b>Link to Website</b>
        sub_title: University of Tokyo
        caption: 2022 (Planned) - Present
        description: |
          -	Investigate the impact of climate change on the variation in pollen seasons across Japan
          -	Explore the association between ozone and temperature and their impact on the suicide rate

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Tokyo
        caption: Mar 2021
        sub_title: MSc in Health Sciences
        description: | # this will include new lines to allow paragraphs
          - Investigated the modifying effect of pollen on the association between air pollution and mortality
          - Graduate Teaching Assistant (Sep 2020 - Oct 2020), [Department of Global Environmental Health](https://sites.google.com/m.u-tokyo.ac.jp/envhealth)
          - Graduate Research Assistant (Jun 2020 - Sep 2020), [Department of Human Ecology](http://www.humeco.m.u-tokyo.ac.jp/en/)

      - layout: left
        title: University of Illinois at Urbana-Champaign
        caption: May 2018
        sub_title: BSc in Chemistry
        description: | # this will include new lines to allow paragraphs
          - Academic Researcher (Mar 2016 - Dec 2018), [National Soybean Research Center](https://icap.sustainability.illinois.edu/place/national-soybean-research-center)
          - Research Assistant (Mar 2016 - Dec 2017), [Illinois Sustainable Research Center](https://www.istc.illinois.edu/)
          - Research Assistant (Jun 2017 - Dec 2017), [Illinois State Water Survey](https://www.isws.illinois.edu/)

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      <b>Software</b>
      - Python
      - R
      - SQL
      - Java
      - Svelte
      - Microsoft Office

      <b>OS & Tools</b>
      - Git
      - Azure
      - Windows
      - Linux
      - Window Subsystem Linux

      <b>Language</b>
      - English (Native)
      - Korean (Fluent)
      - Japanese (Daily)

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Disinfection by-product drivers of cytotoxicity in U.S. drinking water, should other DBPs be regulated?
        link: https://doi.org/10.1021/acs.est.1c07998
        link_text: <b>Link to Publication</b>
        sub_title: Environmental Science & Technology

      - layout: top-middle
        title: Comparison of Estrogenic, Spectroscopic, and Toxicological Analyses of Pilot-Scale Water, Wastewaters, and Processed Wastewaters at Select Military Installations
        link: https://doi.org/10.1021/acs.est.1c00568
        link_text: <b>Link to Publication</b>
        sub_title: Environmental Science & Technology

      - layout: top-middle
        title: The modifying effect of pollen on the association between particulate matter and respiratory mortality, a multi-city analysis in Kyushu, Japan
        link: https://ehp.niehs.nih.gov/doi/abs/10.1289/isee.2021.P-594
        link_text: <b>Link to Publication</b>
        sub_title: ISEE Conference Abstracts

      - layout: top-middle
        title: Assessment of intra-and inter-assay variation in dried blood spot telomere length measurements by qPCR
        link: https://doi.org/10.1537/ase.2011301
        link_text: <b>Link to Publication</b>
        sub_title: Anthropological Science

      - layout: top-middle
        title: Toxicological comparison of water, wastewaters, and processed wastewaters
        link: https://doi.org/10.1021/acs.est.9b00827
        link_text: <b>Link to Publication</b>
        sub_title: Environmental Science & Technology

# Footer
footer_show_references: false
references_title: References available upon request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
