# Site - source: https://github.com/sproogen/modern-resume-theme
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyu Hur
title: Software Engineer (Machine Learning)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: kyuhur2
linkedin_username: kyu-hur-143620b6
orcid_username: 0000-0002-0690-345X
additional_links:
- title: googlescholar
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=p-TpuTsAAAAJ&hl=en
- title: download
  icon: fas fa-file-download
  url: https://github.com/kyuhur2/kyuhur2.github.io/raw/main/resume/Kyu%20Hur%20-%20Resume%20(Software%20Engineering).pdf
# icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Kyu and I am passionate about solving modern day health and business problems with machine learning.

  Please utilize the links in the top right to access any part of my profile and to download my resume.

content:
  - title: Experience (Selected) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FPT Software
        link: https://www.fpt-software.com/
        link_text: FPT Software
        sub_title: Software Engineer
        caption: Feb 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Develop and optimize time-series demand forecasting models utilizing the Python <b>GluonTS</b>, <b>AutoTS</b>, <b>AutoGluon</b> and <b>AutoML</b> frameworks
          -	Communicate directly with the CTO and front-end team to deliver informational dashboards and metrics to non-technical end-users
          -	Deliver presentations of FPT Software’s end-to-end forecasting SaaS product to clients in Japan, South Korea, Malaysia, Germany, and the United States

      - layout: left
        title: Stanford University
        link: https://stanford-health.github.io/
        link_text: Center for Personalized Medicine
        sub_title: Research Intern
        caption: Nov 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Conduct research related to the Wearables Project
          - Draft and edit sections for publications regarding data management

      - layout: left
        title: University of Tokyo
        link: https://www.u-tokyo.ac.jp/en/
        link_text: Department of Human Ecology
        sub_title: Project Researcher
        caption: Nov 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Investigate the impact of climate change on the variation in pollen seasons across Japan
          -	Explore the association between ozone and temperature and their impact on the suicide rate

      - layout: left
        title: Johnson & Johnson
        link: https://www.janssen.com/japan/
        link_text: Janssen Pharmaceutical
        sub_title: Medical Affairs
        caption: Apr 2020 - Dec 2020
        description: | # this will include new lines to allow paragraphs
          -	Spearheaded a three-member project in R to quantify the impact of Macitentan
          - Analyzed clinical data in R to produce in-house reports on the effectiveness of schizophrenia therapies in Japanese populations

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Tokyo
        caption: Mar 2021
        sub_title: MSc in Health Sciences
        description: | # this will include new lines to allow paragraphs
          - Investigated the modifying effect of pollen on the association between air pollution and mortality
          - Graduate Teaching Assistant (Sep 2020 - Oct 2020), [Department of Global Environmental Health](https://sites.google.com/m.u-tokyo.ac.jp/envhealth)
          - Graduate Research Assistant (Jun 2020 - Sep 2020), [Department of Human Ecology](http://www.humeco.m.u-tokyo.ac.jp/en/)

      - layout: left
        title: University of Illinois at Urbana-Champaign
        caption: May 2018
        sub_title: BSc in Chemistry
        description: | # this will include new lines to allow paragraphs
          - Academic Researcher (Mar 2016 - Dec 2018), [National Soybean Research Center](https://icap.sustainability.illinois.edu/place/national-soybean-research-center)
          - Research Assistant (Mar 2016 - Dec 2017), [Illinois Sustainable Research Center](https://www.istc.illinois.edu/)
          - Research Assistant (Jun 2017 - Dec 2017), [Illinois State Water Survey](https://www.isws.illinois.edu/)

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      <b>Software</b>
      - Python
      - R
      - SQL

      <b>Tools & Systems</b>
      - Git
      - AWS/Azure

      <b>Language</b>
      - English (Native)
      - Korean (Native)
      - Japanese (Conversational)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
