# Site - source: https://github.com/sproogen/modern-resume-theme
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyu Hur
title: Software Engineer | Project Researcher | Research Assistant
email: kyuhur2@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: kyuhur2
linkedin_username: kyu-hur-143620b6
orcid_username: 0000-0002-0690-345X

# Additional icon links
additional_links:
- title: googlescholar
  icon: fas google
  url: https://scholar.google.com/citations?user=p-TpuTsAAAAJ&hl=en
# icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Kyu and I am passionate about solving modern-day health and business problems with machine learning.

  I am most skilled in <mark>Python</mark>, <mark>R</mark>, and <mark>SQL</mark>.

content:
  - title: Work Experience (Selected) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FPT Software
        link: https://www.fpt-software.com/
        link_text: FPT Software
        sub_title: Software Engineer
        caption: Feb 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Develop and optimize time-series demand forecasting models utilizing the Python GluonTS, AutoTS, AutoGluon and AutoML frameworks
          -	Communicate directly with the CTO and front-end team to deliver informational PowerBI dashboards and metrics to non-technical end-users
          -	Deliver presentations of FPT Software’s end-to-end forecasting SaaS product to clients in Japan, South Korea, Malaysia, Germany, and the United States
          -	Utilize Agile methodologies while managing a collaborative water demand forecasting project to meet the needs of a Malaysian, state-owned enterprise
          -	Oversee day-to-day duties and long-term goals of three data science interns

      - layout: left
        title: Stanford University
        link: https://stanford-health.github.io/
        link_text: Stanford University
        sub_title: Research Intern
        caption: Nov 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Wearables Project

      - layout: left
        title: University of Tokyo
        link: https://www.u-tokyo.ac.jp/en/
        link_text: University of Tokyo
        sub_title: Project Researcher
        caption: Nov 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Investigate the 30-year impact of climate change on the variation in pollen seasons across Japan
          -	Explore the association between ozone and temperature and their impact on the suicide rate

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Tokyo
        caption: 2019 - 2021
        sub_title: Masters of Science in Health Sciences
        description: | # this will include new lines to allow paragraphs
          - Investigated the modifying effect of pollen on the association between air pollution and mortality
          - Graduate Teaching Assistant, [Department of Global Environmental Health](https://sites.google.com/m.u-tokyo.ac.jp/envhealth) (Environmental Health and Research Methods)
          - Graduate Research Assistant, [Department of Human Ecology](http://www.humeco.m.u-tokyo.ac.jp/en/)

      - layout: left
        title: University of Illinois at Urbana-Champaign
        caption: 2013 - 2018
        sub_title: Bachelors of Science in Liberal Arts & Sciences, Chemistry
        description: | # this will include new lines to allow paragraphs
          - Academic Researcher, [National Soybean Research Center](https://icap.sustainability.illinois.edu/place/national-soybean-research-center)
          - Research Assistant, [Illinois Sustainable Research Center](https://www.istc.illinois.edu/)
          - Research Assistant, [Illinois State Water Survey](https://www.isws.illinois.edu/)

  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
