export { About } from './About'
export { Education } from './Education'
export { Experience } from './Experience'
export { Footer } from './Footer'
export { Header } from './Header'
export { Home } from './Home'
export { Projects } from './Projects'
export { Contact } from './Contact'
