# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Setup nodejs
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    
    # Install dependencies 
    - name: Install dependencies
      run: yarn install

    # Build
    - name: Build
      run: yarn build
    
    # List output files
    - name: List output files
      run: ls
    
    # Deploy to server
    - name: FTP Deployment
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: build/ # This folder is NOT going to upload by default unless you add it to .git-ftp-include
